### ISSUE TITLE
No 1.17.1 download?

### ISSUE THREAD

**Issue by Ferret-Dev** [ItsKaitlyn03/SmoothedController#1]
The 1.17.1 release appears to be missing. You can't even download from the discord link. Can you please reinstate it, or at least give us a new link? 1.17.1 is still very relevant, due to it being the latest good update with access to replays and qosmetics.

**Comment by Ferret-Dev** [comment]
My bad, I didn't realize you had an old version repo. However, could you please update the discord link, as to not confuse others who are looking for the mod? 

https://github.com/ItsKaitlyn03/SmoothedController-old/releases/tag/v1.2.0

**Comment by whatdahopper** [comment]
Fixed.
